# Copyright 2020-2023 Practically.io All rights reserved
version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    commit-message:
      prefix: 'chore:'
    ignore:
      - dependency-name: 'got'
        versions: ['12.x']
      - dependency-name: 'execa'
        versions: ['6.x']
      - dependency-name: 'chalk'
        versions: ['5.x']
    assignees:
      - 'george'
    labels:
      - 'priority: normal'
      - 'status: to do'
      - 'type: task'
      - 'component: dependencies'
