# Copyright 2023 Practically.io All rights reserved
git:
  provider: github
  project: Practically/conventional-tools
hooks:
  commit-msg:
    - ./bin/run commitlint -f HEAD~2
  pre-push:
    - ./bin/run commitlint -l1
  prepare-commit-msg:
    - |
      # Commitgen
      if [ -z "${2}" ]; then
        echo "$(conventional-tools commitgen)$(cat ${1})" > ${1};
      fi
  pre-commit:
    - $(conventional-tools root)/.github/hooks/check-copyright.sh
    - $(conventional-tools root)/.github/hooks/no-yaml-files.sh
    - $(conventional-tools root)/.github/hooks/prettier.sh
commit:
  scopes:
    - core
    - changelog
    - commitgen
    - commitlint
    - release
    - release-semver
    - release-calver
    - git-hooks
assets:
  - dist/*
