# Copyright 2022 Practically.io All rights reserved
git:
  provider: gitlab
  host: git.zportal.co.uk
  project: practically-oss/conventional-tools
hooks:
  commit-msg:
    - ./bin/run commitlint -f HEAD~2
  pre-push:
    - ./bin/run commitlint -l1
  prepare-commit-msg:
    - |
      # Commitgen
      if [ -z "${2}" ]; then
        echo "$(conventional-tools commitgen)$(cat ${1})" > ${1};
      fi
  pre-commit:
    - $(git rev-parse --show-toplevel)/.gitlab/hooks/check-email.sh
    - $(git rev-parse --show-toplevel)/.gitlab/hooks/check-copyright.sh
    - $(git rev-parse --show-toplevel)/.gitlab/hooks/no-yaml-files.sh
    - $(git rev-parse --show-toplevel)/.gitlab/hooks/prettier.sh
commit:
  scopes:
    - core
    - changelog
    - commitgen
    - commitlint
    - release
    - release-semver
    - release-calver
    - git-hooks
assets:
  - dist/*
