version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  commit-message:
    prefix: "chore:"
  assignees:
    - "ade"
  labels:
    - "priority: normal"
    - "status: to do"
    - "type: task"
    - "component: dependencies"
