version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  commit-message:
    prefix: "chore:"
  ignore:
    - dependency-name: 'got'
      versions: ['12.x']
    - dependency-name: 'execa'
      versions: ['6.x']
  assignees:
    - "ade"
  labels:
    - "priority: normal"
    - "status: to do"
    - "type: task"
    - "component: dependencies"
