# Copyright 2023 Practically.io All rights reserved

name: CI

on:
  push: { branches: ["2.x"] }
  pull_request: { branches: ["2.x"] }

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Node ${{ matrix.node-version }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Setup environment
        run: |
          ln -s $(pwd)/bin/conventional-tools.js /usr/local/bin/conventional-tools
          git config --global user.email "test@test.com"
          git config --global user.name "Tester"

      - name: Lint
        run: yarn lint

      - name: Type Check
        run: yarn build

      - name: Test
        run: yarn test
